### ISSUE TITLE
Does this work with the Seeed Xiao RP2040?

### ISSUE THREAD

**Issue by 15medium** [nealey/vail-adapter#3]
Does this work with the Seeed Xiao RP2040?
https://wiki.seeedstudio.com/XIAO-RP2040/
Holding the boot button and plugging it in brings up the device but nothing happens when I copy the vail-adapter.xiao.uf2 file to it.
Thanks,
Paul VA3ZC

**Comment by nealey** [comment]
No, it doesn't. Thanks for sending me a compile error log in private email, that saved me a bunch of time.

I've updated the documentation to specifically mention the M0 as the board to get. I hope nobody else has tried to get it on the wrong board!

**Comment by nealey** [comment]
Fixed in https://github.com/nealey/vail-adapter/commit/36cc1384431d4a01a2066e536f0696d9a95e30b6
